### ISSUE TITLE
Curios will get destroyed if you die with full inventory and then die again before collecting

### ISSUE THREAD

**Issue by theboo** [Quarris/EnigmaticGraves#3] opened 2021-07-04 20:08 UTC
If you die with a full inventory and curios equipped, and then die again before collecting the first grave, all curios you had equipped will be yeeted out of existence. Tested both in SP and on a server.

Steps to repro:
1: get a full inventory and some curios equipped
2: die
3: die again
4: collect the graves and all curios will be gone instead of dropped as items on the ground as other things are.

As a side note: if you die with curios equipped without a full inventory, then die again before retrieving the grave, you will get ur curios back but they will not be in their slots, rather they are placed in the main inventory.

Found this issue trying to reproduce the exact opposite issue i've seen twice now where after dying a bunch and collecting the first grave ONLY curios were returned to my inventory, but i have yet to be able to reproduce reliably, just happened twice in normal gameplay.

**Comment by Quarris** [comment] 2021-07-05 23:06
I accidently tested your way of reproduction wrong, and got similar results, I fixed those results and I couldn't reproduce your issue so I think it might be fixed.
Could you test this to see if your issue persists?
https://drive.google.com/file/d/1byZSZ4jt0oNcw0p-KIuk2eWMpdArxHlR/view?usp=sharing

**Comment by theboo** [comment] 2021-07-07 13:45
for whatever reason i didnt get a notification for this... ill test it tonight!

**Comment by Quarris** [comment] 2021-07-07 13:47
I already uploaded it to cf because it felt pretty breaking. But do let me know if you find any issues!

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Quarris** [comment] 2021-07-07 15:27
Ill close this for now, reopen if the issue persists.

**Closed by Quarris** 2021-07-07 15:27 UTC
